dist: xenial
language: python
sudo: true
cache:
- pip
python:
- '3.7'
install:
- pip install pipenv --upgrade
- pipenv sync --dev
addons:
  postgresql: '10'
before_script:
- psql -c 'create database fccopif;' -U postgres
env:
  global:
  - DJANGO_ENV=prod
  - PIPENV_VERBOSITY=-1
  - secure: cxew5HT/eRM9J6SW47LNdR7FXNt95liUEgUtfdTJOTGB5VqCQxWBY44Qz5bJAAP/f2/gCaFlR8ZY9SGoJmeKiVpicW18TORpEeW0GC71FB3ONXuh1LEhA0JQUBgu7nP2k7Qh0NpTCCLouICIUfsWKrE3xHm1vNfnUddj1n96B/0dJ/VbSOtO17UOTuo8hplKwxo82ftqmEqh3GoqerfuxXhKpYVfv/xUlai4E/SrGJC6mmwFqeq2TlHOabYBeUzopAcXjAzI32NVDhjniv75+hW4Dx+iPwJ3224v4301q/iR2EV1Wnx7DGLvlNarjEuDEUoLvqzG6tN4Nck7wQYzRiEXn/7b/9JYG3Vb3AFHeMvjF46CRkxzBUpDNfwKp74OhOB8duI76OJRfqCRR/E1dCjrknUerTzNxBxlHwS37H8QIfWtBEkcihtae29GSRPvX94OxUw4SDYC94Lg10CXDLtYzbmjQY59Jh12SAdktwfIbe0UPGQoiWjgy6KGOFxvtPsop1C56dfJaxF7GJY1L0AI8jgXJll/vwxaXKDC9rNG7xvKwCSqA9J+v1yv1P4bD/J5/vV1fVk1PezZX+AlJXjSPjx5RUmWQQX7GW1UYWfLuNce83Hg1DpFvODMumPgWWnjhfLlOHi2rsNLsg004UmgYbjCtzunB1pGv4gMHaM=
  - secure: OMj4YOuhZ/aax0w4Pr3lBKEW8IXamk5u3OE2Z9dxAuc3/NY0MZuPnwVcIFZWUyCZegNfT3eekYN6+y3zDsv01OmQ5xrfpqTgEOnX957Op0UgcaeYYcQ81aTw0pkCzBdjE2nJ7Ggu8g689p5JM4b03ImjIabzP/w338eH3S8tQdQiCEwoerTxtwVcIR/WRJTwH2BWNpGRBzf/wyRQYEDZ2+iuEHHUAYceIbabtLC8IJp+nuBciWiRFwsD/6QeTXzJFs2tuxOFjuJdc5QZafXV36UVebyh0XX7wb/I8nAArzxzbdFifKStWsz+OjM6TGp9LkzRP91yVF+J7PKJlj9R5cpzxSPei1wd242Vd1uO00J3URb5Inho/ohvR1eQ/sYjLuQbANtVVvUejzq2UxQL2z/X6XZmvgfXl3vvBY6tMHTJT90bCbj+B0mzyOCcsE8yBFm0Gx4XjV4lOYYl2mIL2u43x7tHU9QvnDqCs94cAvlyPjefjpL6Z3fBEv86+SstRxx6B3l1jt3Ju0ITtagEvoO+CDTBLPqGtzfSCGwgeOkDsZW4uPGnww4GJVdxHIxDocMTxRiCkyTobCU7R804Qebp9+EnSJJ06FvgL6kMhVSL8ItjAKJCYQM5HPUYY51r5wCqmyj7KHmiVtua+JbyMzf/fzf5NWd7Ll31pSffI/c=
script:
- make test
after_success:
- test $TRAVIS_BRANCH = “master” && zappa update prod && zappa manage prod 'migrate'
before_install:
- openssl aes-256-cbc -K $encrypted_2e6f30dbbe15_key -iv $encrypted_2e6f30dbbe15_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
