# Generated by Django 2.2.4 on 2019-09-06 18:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('call_sign', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('am', 'AM'), ('fm', 'FM'), ('tv', 'TV')], max_length=2)),
                ('rf_channel', models.IntegerField()),
                ('virtual_channel', models.IntegerField()),
                ('license_expiration_date', models.CharField(max_length=10)),
                ('status_date', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=200)),
                ('community_city', models.CharField(max_length=200)),
                ('community_state', models.CharField(max_length=2)),
                ('facility_type', models.CharField(max_length=200)),
                ('frequency', models.DecimalField(decimal_places=1, max_digits=4)),
                ('active_ind', models.BooleanField()),
                ('scanned_letter_ids', models.CharField(blank=True, max_length=200)),
                ('party_name', models.CharField(max_length=200)),
                ('party_address1', models.CharField(max_length=200)),
                ('party_address2', models.CharField(max_length=200)),
                ('party_city', models.CharField(max_length=200)),
                ('party_zip1', models.CharField(max_length=5)),
                ('party_zip2', models.CharField(blank=True, max_length=5)),
                ('party_state', models.CharField(max_length=2)),
                ('party_phone', models.CharField(max_length=13)),
                ('nielsen_dma', models.CharField(max_length=200)),
                ('network_afil', models.CharField(max_length=200)),
                ('band', models.CharField(max_length=200)),
                ('auth_app_id', models.CharField(max_length=7)),
                ('post_card_id', models.CharField(max_length=7)),
                ('main_studio_contact', django.contrib.postgres.fields.jsonb.JSONField()),
                ('cc_contact', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('entity_folder_id', models.UUIDField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(max_length=200)),
                ('folder_path', models.CharField(max_length=200)),
                ('allow_rename_ind', models.BooleanField()),
                ('allow_subfolder_ind', models.BooleanField()),
                ('allow_upload_ind', models.BooleanField()),
                ('allow_delete_ind', models.BooleanField()),
                ('more_public_files_ind', models.BooleanField(default=False)),
                ('file_count', models.IntegerField(null=True)),
                ('create_ts', models.CharField(max_length=200)),
                ('last_update_ts', models.CharField(max_length=200)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='fcc_opif.Facility')),
                ('parent_folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='fcc_opif.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.UUIDField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=200)),
                ('file_extension', models.CharField(max_length=3)),
                ('file_size', models.IntegerField(null=True)),
                ('file_status', models.CharField(max_length=200)),
                ('create_ts', models.CharField(max_length=200)),
                ('last_update_ts', models.CharField(max_length=200)),
                ('file_manager_id', models.CharField(max_length=200)),
                ('moved_from', models.CharField(max_length=200, null=True)),
                ('moved_ts', models.CharField(max_length=200, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='fcc_opif.Folder')),
            ],
        ),
    ]
