# Generated by Django 2.2.4 on 2019-08-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_opif', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='frequency',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facility',
            name='party_zip_2',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='facility',
            name='scanned_letter_ids',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
