# Generated by Django 2.2.6 on 2019-11-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_opif', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cablefile',
            name='create_ts',
            field=models.DateTimeField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cablefile',
            name='last_update_ts',
            field=models.DateTimeField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cablefolder',
            name='create_ts',
            field=models.DateTimeField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cablefolder',
            name='last_update_ts',
            field=models.DateTimeField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facilityfile',
            name='create_ts',
            field=models.DateTimeField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facilityfile',
            name='last_update_ts',
            field=models.DateTimeField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facilityfolder',
            name='create_ts',
            field=models.DateTimeField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facilityfolder',
            name='last_update_ts',
            field=models.DateTimeField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
