# Generated by Django 2.2.5 on 2019-09-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_opif', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='documentcloud_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
