# Generated by Django 2.2.5 on 2019-09-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_opif', '0002_auto_20190918_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='rf_channel',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='virtual_channel',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
