# Generated by Django 2.2.7 on 2019-11-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_opif', '0002_auto_20191119_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='frequency',
            field=models.DecimalField(decimal_places=1, editable=False, max_digits=5, null=True),
        ),
    ]
