# Generated by Django 2.2.4 on 2019-08-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_opif', '0002_auto_20190828_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='frequency',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
