# Generated by Django 2.2.5 on 2019-09-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_opif', '0003_auto_20190923_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='frequency',
            field=models.DecimalField(decimal_places=1, editable=False, max_digits=5),
        ),
    ]
