# Generated by Django 2.2.6 on 2019-11-21 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_opif', '0003_auto_20191120_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cablefile',
            name='missing_stored_file',
        ),
        migrations.RemoveField(
            model_name='cablefolder',
            name='_actual_file_count',
        ),
        migrations.RemoveField(
            model_name='cablesystem',
            name='_actual_file_count',
        ),
        migrations.RemoveField(
            model_name='cablesystem',
            name='_expected_file_count',
        ),
        migrations.RemoveField(
            model_name='cablesystem',
            name='has_missing_files',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='_actual_file_count',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='_expected_file_count',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='has_missing_files',
        ),
        migrations.RemoveField(
            model_name='facilityfile',
            name='missing_stored_file',
        ),
        migrations.RemoveField(
            model_name='facilityfolder',
            name='_actual_file_count',
        ),
    ]
