# Generated by Django 2.2.4 on 2019-08-29 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_opif', '0003_auto_20190828_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='facility',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fcc_opif.Facility'),
        ),
    ]
