# Generated by Django 2.2.4 on 2019-08-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_opif', '0004_file_facility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Facility', 'verbose_name_plural': 'Facilities'},
        ),
    ]
