# Generated by Django 2.2.6 on 2019-11-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_opif', '0004_auto_20191121_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cablesystem',
            old_name='local_file_zipcode',
            new_name='local_file_zip_code',
        ),
        migrations.RenameField(
            model_name='cablesystem',
            old_name='local_file_zipcode_suffix',
            new_name='local_file_zip_code_suffix',
        ),
        migrations.RenameField(
            model_name='cablesystem',
            old_name='operator_zipcode',
            new_name='operator_zip_code',
        ),
        migrations.RenameField(
            model_name='cablesystem',
            old_name='operator_zipcode_suffix',
            new_name='operator_zip_code_suffix',
        ),
        migrations.RenameField(
            model_name='cablesystem',
            old_name='principal_zipcode',
            new_name='principal_zip_code',
        ),
        migrations.RenameField(
            model_name='cablesystem',
            old_name='principal_zipcode_suffix',
            new_name='principal_zip_code_suffix',
        ),
    ]
