# Generated by Django 2.2.5 on 2019-09-23 21:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_opif', '0004_auto_20190923_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='cc_contact',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False),
        ),
    ]
