# Generated by Django 2.2.6 on 2020-02-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_opif', '0005_auto_20191122_1246'),
        ('fcc_opif', '0004_auto_20191122_1227'),
    ]

    operations = [
    ]
