# Generated by Django 3.0.3 on 2020-02-14 20:40

from django.db import migrations, models
import django.db.models.deletion
import fcc_opif.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_opif', '0006_merge_20200204_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePageBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=fcc_opif.models.base.get_upload_path)),
                ('page_num', models.IntegerField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityFilePage',
            fields=[
                ('filepagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fcc_opif.FilePageBase')),
                ('file', models.ForeignKey(db_column='file_id', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='file_pages', to='fcc_opif.FacilityFile')),
            ],
            bases=('fcc_opif.filepagebase',),
        ),
        migrations.CreateModel(
            name='CableFilePage',
            fields=[
                ('filepagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fcc_opif.FilePageBase')),
                ('file', models.ForeignKey(db_column='file_id', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='file_pages', to='fcc_opif.CableFile')),
            ],
            bases=('fcc_opif.filepagebase',),
        ),
    ]
