# Generated by Django 2.2.5 on 2019-09-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_opif', '0006_auto_20190923_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cablefile',
            name='file_extension',
            field=models.CharField(editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='facilityfile',
            name='file_extension',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
