# Generated by Django 2.2.5 on 2019-09-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_opif', '0007_auto_20190923_1634'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cablefile',
            index=models.Index(fields=['file_name'], name='fcc_opif_ca_file_na_a8d5da_idx'),
        ),
        migrations.AddIndex(
            model_name='cablefolder',
            index=models.Index(fields=['folder_path'], name='fcc_opif_ca_folder__8a06b8_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['service_type', 'call_sign'], name='fcc_opif_fa_service_d57b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityfile',
            index=models.Index(fields=['file_name'], name='fcc_opif_fa_file_na_5b851c_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityfolder',
            index=models.Index(fields=['folder_path'], name='fcc_opif_fa_folder__c97511_idx'),
        ),
    ]
