# Generated by Django 3.0.3 on 2020-02-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_opif', '0007_cablefilepage_facilityfilepage_filepagebase'),
    ]

    operations = [
        migrations.AddField(
            model_name='cablesystem',
            name='last_refreshed_ts',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
