# Generated by Django 3.0.5 on 2020-04-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_opif', '0008_cablesystem_last_refreshed_ts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityfilepage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='facilityfilepage',
            name='filepagebase_ptr',
        ),
        migrations.DeleteModel(
            name='CableFilePage',
        ),
        migrations.DeleteModel(
            name='FacilityFilePage',
        ),
        migrations.DeleteModel(
            name='FilePageBase',
        ),
    ]
