# Generated by Django 3.0.5 on 2020-04-14 18:49

from django.db import migrations, models
import django.db.models.deletion
import fcc_opif.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_opif', '0009_auto_20200414_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityFilePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=fcc_opif.models.base.get_upload_path)),
                ('page_num', models.IntegerField(editable=False, null=True)),
                ('file', models.ForeignKey(db_column='file_id', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='file_pages', to='fcc_opif.FacilityFile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CableFilePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=fcc_opif.models.base.get_upload_path)),
                ('page_num', models.IntegerField(editable=False, null=True)),
                ('file', models.ForeignKey(db_column='file_id', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='file_pages', to='fcc_opif.CableFile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
