# Generated by Django 3.0.5 on 2020-05-01 21:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_opif', '0010_cablefilepage_facilityfilepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('boxes', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ocr_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('proto_file_field', models.UUIDField(editable=False)),
            ],
        ),
    ]
