# Generated by Django 3.0.5 on 2020-05-01 21:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcc_opif', '0012_auto_20200501_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileform',
            name='boxes',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='fileform',
            name='ocr_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
